[project]
name = "dbt-bq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dbt-bigquery>=1.10.3",
    "dbt-core>=1.10.15",
]
